services:
  - type: web
    name: its-all-hers
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~kJUGsiIv"
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
